project:
  type: website
  output-dir: docs
  render:
    - '*.qmd'
    - 'posts/'
    - '!notebooks/'
    - '!notes/'
    - '!tests/'

website:
  title: 'Practice in Code'
  site-url: "https://tlint101.github.io/practice-in-code/"
  description: 'Practice in Code'
  page-footer: 'Website made with [Quarto](https://quarto.org/) and a teeny bit of ❤️ by Tony E. Lin'
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tlint101/practice-in-code/
      - icon: rss
        href: index.xml
  google-analytics: "G-DKY2WMQ374"
  search: true
format:
  html:
    toc: true
    toc-depth: 3      # ensures H3 headers are included
    toc-expand: 3     # ensures the menu expands
    theme:
      light: [flatly, css/light.css]
      dark: [darkly, css/dark.css]

comments:
  utterances:
    repo: https://github.com/tlint101/practice-in-code/tree/main

execute:
  freeze: auto
  