name: blog
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rdkit
  - pip:
      - py50==0.1.0
      - notebook==7.0.6
      - scikit-learn
      - pingouin
      - scikit-posthocs
      - datamol
      - marimo
      - marimo-chem-utils
